export const SAVE_SELECTED_CUISINE = 'SAVE_SELECTED_CUISINE';
export const INIT_EMPTY_CUISINE_STATE = 'INIT_EMPTY_CUISINE_STATE';
export const FETCH_MEAL_ITEMS_BY_CUISINE = 'FETCH_MEAL_ITEMS_BY_CUISINE';
export const FETCH_MEAL_DESCRIPTION_BY_ID = 'FETCH_MEAL_DESCRIPTION_BY_ID';
export const FETCH_MEAL_ITEMS_FAILED = 'FETCH_MEAL_ITEMS_FAILED';
export const FETCH_MEAL_DESCRIPTION_FAILED = 'FETCH_MEAL_DESCRIPTION_FAILED';
export const SAVE_MEALS_BY_CUISINE = 'SAVE_MEALS_BY_CUISINE';
export const SAVE_MEAL_DESCRIPTION_BY_CUISINE = 'SAVE_MEAL_DESCRIPTION_BY_CUISINE';